
spring:
  application:
    name: service-consumer
server:
  port: 8082
logging:
  level:
    com.mfma.serviceconsumer: debug



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://mfma:123456@eureka-server.com:8761/eureka/,http://mfma1:1234567@eureka-slave-server-1.com:8762/eureka/,http://mfma2:12345678@eureka-slave-2-second.com:8763/eureka/}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}